import Head from "next/head";
import FileContainer from "../components/fileContainer/FileContainer";
import VsEditor from "../components/VSEditor/VsEditor";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Langesh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FileContainer />
      <VsEditor />
    </div>
  );
}
