import Head from "next/head";
import Image from "next/image";
import Editor from "@monaco-editor/react";

export default function Home() {
  function changeHandler(value, event) {
    document.getElementById("output").innerHTML = value;
    const output = eval(value);
    console.log(output);
  }

  return (
    <div className="bg-blue-400">
      <Head>
        <title>Langesh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        <Editor
          width="60%"
          height="100vh"
          defaultLanguage="javascript"
          defaultValue="console.log('Hello World');"
          theme="vs-dark"
          onChange={changeHandler}
        />
        <section id="output" className="h-screen flex-1 bg-white"></section>
      </main>
    </div>
  );
}
